---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(dataRetrieval)
library(lubridate)
```

Create table with available parameters and periods for each gage in NC lowdev dataset
```{r}
#sites <- read_csv("serefsites.csv")$sites
#sites <- paste("0",as.character(sites), sep = '')
sites <- read_csv("Sites_May2020_CONUS.csv")$STAID 

#sites <- sites[1:282]

#pull available daily data and match with parameter names from parameterCdFile , service="dv", statCd = "00003"
# available <- whatNWISdata(siteNumber = sites, service = c("dv","qw")) %>%
#   select(c("site_no","station_nm","dec_lat_va", "dec_long_va","parm_cd","stat_cd","begin_date","end_date")) %>%
#   left_join(parameterCdFile, by = c("parm_cd" = "parameter_cd"))
# 
# bystation <- pivot_wider(available, id_cols = c("site_no","station_nm"), names_from = "parameter_nm", 
#                          values_from = "parameter_nm",
#                          values_fn = list(parameter_nm = length))
# 
# #pull out sites that have instantaneous data available
# sites_inst <- bystation %>% select(site_no, 'Discharge, instantaneous, cubic feet per second') %>%
#   drop_na() %>% select(site_no)
# 
# write_csv(sites_inst, "sites_inst_ref_urban.csv")

```

USE THIS FOR INSTANTANEOUS VALUES
```{r}
param <- "00060" #discharge
#stat codes max 00001 min 00002 mean 00003
stat <- "00003"

     sitesDL <- sites[1:300]
    ###change for instantaneous values... daily right now
     data <- readNWISdv(siteNumbers = sitesDL, parameterCd = param, startDate = "1999-01-01", endDate = "1999-12-31")
   
    for(x in 2000:2010){
      start <- paste(x,"-01-01", sep = '')
      end <- paste(x, "-12-31", sep = '')
      
      
      datanew <- readNWISuv(siteNumbers = sitesDL, parameterCd = param, startDate = start, endDate = end)
      
      data <- bind_rows(data, datanew)
    }
    
    write_csv(data, paste("daily_data_CONUS_1999-2010_300", indexes[z], ".csv" ,sep = ''))


```

```{r}
#create daily summaries

for(t in 1:7){
  #read data to make daily
  data <- read_csv(paste("inst_data_2000-2010_ref_urban_",t,"00.csv", sep = ""))
  #max #min #mean #median #sd #count
  datsum <- data %>% group_by(site_no, year(dateTime), month(dateTime), day(dateTime)) %>%
            summarise(min(X_00060_00000), mean(X_00060_00000), max(X_00060_00000), sd(X_00060_00000), length(X_00060_00000)) %>%
            rename('year' = 'year(dateTime)', 'month' = 'month(dateTime)', 'day' = 'day(dateTime)',
                   'minDaily' = 'min(X_00060_00000)','meanDaily' = 'mean(X_00060_00000)',
                   'maxDaily' = 'max(X_00060_00000)','sdDaily' = 'sd(X_00060_00000)',
                   'lenDaily' = 'length(X_00060_00000)') %>%
            mutate(date = mdy(paste(month, day, year))) %>%
            ungroup() %>%
            select(site_no, date, minDaily, meanDaily, maxDaily, sdDaily, lenDaily)
  
  write_csv(datsum, paste("dailystatsALL_ref_urban_",t,"00.csv", sep = ""))
}
```
```{r}
#combine daily files into one

for(t in 1:7){
  
  if(t == 1) data <- read_csv(paste("dailystatsALL_ref_urban_",t,"00.csv", sep = ""))
  
  if(t > 1){
    datanew <- read_csv(paste("dailystatsALL_ref_urban_",t,"00.csv", sep = ""))
    datanew <- datanew %>% mutate(site_no = as.character(site_no))
    data <- bind_rows(data, datanew)
  }
  
}

write_csv(data, "all_ref_sites_daily_stats.csv")
```
DAILY VALUES
```{r}
param <- "00060" #discharge
#stat codes max 00001 min 00002 mean 00003
stat <- "00003"

     
  data <- readNWISdv(siteNumbers = sites[701], parameterCd = param, startDate = "1999-01-01", endDate = "2010-12-31")
   
   for(x in 702:1148){ #length(sites)){
    
      datanew <- readNWISdv(siteNumbers = sites[x], parameterCd = param, startDate = "1999-01-01", endDate = "2010-12-31")
      
      data <- bind_rows(data, datanew)

    }
    write_csv(data, paste("daily_data_CONUS_1999-2010_to1148.csv" ,sep = ''))


```

```{r}
#combine two data files
data1 <- read_csv("daily_data_CONUS_1999-2010_to700.csv")

data <- bind_rows(data, data1)

write_csv(data, "daily_data_CONUS_1999-2010.csv")
```

