---
title: "R Notebook"
output: html_notebook
---

```{r}
library(viridis)
library(tidyverse)
library(lubridate)
```


```{r}
library(patchwork)
library(rgdal)
info <- read_csv("all_ref_urban.csv")

ranks <- read_csv("RanksAndSummaries_all_sites.csv")

yearlystats <- read_csv("YearlyStats_all_CONUS.csv")

allstats <- left_join(yearlystats, info, by = c("site_no" = "STAID"))
#add size classes
RBIbreaks <- c(0,78,260,780,2600,7800,30000)
RBInames <- c("a","b","c","d","e","f")
Breaks <- c(0,39,78,260,780,2600,7800,30000)
Breaksnames <- c("aa","a","b","c","d","e","f")

#df1 <- df %>% mutate(category=cut(a, breaks=xs, labels=c("low","middle","high")))
allstats <- allstats %>% 
  mutate(RBpaperSize = cut(DRAIN_SQKM, breaks = RBIbreaks, labels = RBInames)) %>%
  mutate(newSize = cut(DRAIN_SQKM, breaks = Breaks, labels = Breaksnames))

write_csv(allstats, "yearly_stats_w_attributes_all.csv")

ranks <- left_join(ranks, info, by = c("site_no" = "STAID"))

ranks <- ranks %>% 
  mutate(RBpaperSize = cut(DRAIN_SQKM, breaks = RBIbreaks, labels = RBInames)) %>%
  mutate(newSize = cut(DRAIN_SQKM, breaks = Breaks, labels = Breaksnames))

write_csv(ranks, "stats_ranks_attributes_per_site_all.csv")

setwd("/Volumes/GoogleDrive/My Drive/flowstats_GZK/cb_2018_us_state_500k")
states <- readOGR("cb_2018_us_state_500k.shp")
```

```{r}
allstats %>%
  filter(year == 2007) %>%
  ggplot(aes(LNG_GAGE, LAT_GAGE, color = log(RBImax)))+
    geom_point()+
    scale_color_viridis("RBI max")
```

```{r}
RMR <- ranks %>%
  ggplot(aes(LNG_GAGE, LAT_GAGE, color = RBImaxrank))+
    geom_point()+
    scale_color_viridis("RBI max rank")
```

```{r}
RR <- ranks %>%
  ggplot(aes(LNG_GAGE, LAT_GAGE, color = RBIrank))+
    geom_point()+
    scale_color_viridis("RBI rank")

RR / RMR
```

```{r}
#rank if you use mean - rank using max
#Negative means max rank is a bigger number, which means you becamse more flashy


#world.map <- world.map[world.map$AREA > 30000,]
cstates <- states[!states$STUSPS %in% c("HI","AK","PR","VI","GU","MP","AS"),] 

ranks %>% filter(RBImax < .05) %>%
  ggplot(aes(LNG_GAGE, LAT_GAGE, fill = RBI))+
  geom_polygon(data = cstates, aes(x = long, y = lat, group = group), colour = "black", fill = NA)+
    geom_point(colour = "black", pch = 21)+
   # scale_fill_gradient2()+
  scale_fill_viridis()+
  
  theme_classic()
```
```{r}
ranks %>% filter(DEVNLCD06 > 20) %>%
  ggplot(aes(RBI, RBImax, color = DEVNLCD06), alpha = .5)+
    geom_point()+
  scale_color_viridis()+
  theme_classic()
  #scale_x_log10()
    
```
```{r}
#rank if you use mean - rank using max
#Negative means max rank is a bigger number, which means you becamse more flashy

ranks %>% #filter(RBI < 1.2) %>%
  ggplot(aes(x =  GEOL_HUNT_DOM_DESC, y = RBIrank - RBImaxrank))+
    geom_boxplot()
    scale_fill_gradient2()+
  #scale_fill_viridis()+
  #geom_polygon(data = states, aes(x = long, y = lat, group = group), colour = "black", fill = NA)
  theme_classic()
```

```{r, fig.height=15, fig.width=6}
allstats %>%
  ggplot(aes(x = site_no, y = RBI, fill = "RBI"))+
    geom_boxplot() +
    geom_boxplot(aes(x = site_no, y = RBImax, fill = "RBImax"))+
    geom_boxplot(aes(x = site_no, y = RBImm, fill = "RBImax-mean"))+
    ylim(c(0,5))+
    coord_flip()+
    theme_classic()+
    scale_colour_manual(name = 'RBI type')+
    facet_grid(rows = "Type")
    
```
```{r}
rmax <- allstats %>%
    ggplot(aes(x = Type, y = RBImax))+
    geom_boxplot()+
    theme_classic()+
    ylim(c(0,20))

rreg <- allstats %>%
    ggplot(aes(x = Type, y = RBI))+
    geom_boxplot()+
    theme_classic()+
    ylim(c(0,20))

rmm <- allstats %>%
    ggplot(aes(x = Type, y = RBImm))+
    geom_boxplot()+
    theme_classic()+
    ylim(c(0,20))

rreg + rmax + rmm
```

```{r}
darbi <- allstats %>%
  ggplot(aes(y = RBI, x = DRAIN_SQKM, color = Type))+
  geom_point()+
  theme_classic()+
  theme(legend.position = 'none')

darbimax <- allstats %>%
  ggplot(aes(y = RBImax, x = DRAIN_SQKM, color = Type))+
  geom_point()+
  theme_classic()+
  theme(legend.position = 'none')

darbimm <- allstats %>%
  ggplot(aes(y = RBImm, x = DRAIN_SQKM, color = Type))+
  geom_point()+
  theme_classic()+
  theme(legend.position = 'none')

darbi + darbimax + darbimm
```
```{r, fig.height=4, fig.width=4}
# function for number of observations 
give.n <- function(x){
  #return(c(y = median(x)*1.05, label = length(x))) 
  return(c(y = 1.5, label = length(x))) 
  # experiment with the multiplier to find the perfect position
}

rbpaperplot <- ranks %>%
  ggplot(aes(x = RBpaperSize, y = RBI, fill = Type)) +
  geom_boxplot() +
  ylim(c(0,1.5)) +
  theme_classic() +
  stat_summary(fun.data = give.n, geom = "text", fun = median, hjust = 0.5, position = position_dodge(1))

newsizeplot <- ranks %>%
  ggplot(aes(x = newSize, y = RBI, fill = Type)) +
  geom_boxplot() +
  ylim(c(0,1.5)) +
  theme_classic()+
  stat_summary(fun.data = give.n, geom = "text", fun = median, hjust = 0.5, position = position_dodge(1))


rbpaperplotMAX <- ranks %>%
  ggplot(aes(x = RBpaperSize, y = RBImax, fill = Type)) +
  geom_boxplot() +
  ylim(c(0,1.5)) +
  theme_classic()+
  stat_summary(fun.data = give.n, geom = "text", fun = median, hjust = 0.5, position = position_dodge(1))


newsizeplotMAX <- ranks %>%
  ggplot(aes(x = newSize, y = RBImax, fill = Type)) +
  geom_boxplot() +
  ylim(c(0,1.5)) +
  theme_classic()+
  stat_summary(fun.data = give.n, geom = "text", fun = median, hjust = 0.5, position = position_dodge(1))


combined <- (rbpaperplot + newsizeplot) / (rbpaperplotMAX + newsizeplotMAX) & theme(legend.position = "bottom")
combined + plot_layout(guides = "collect")
```
```{r}

cols <- c("gray", "red")

sizeRBI <- ranks %>% filter(RBI < 4) %>% #there is an "inf" value...
  ggplot(aes(x = DRAIN_SQKM, y = RBI, color = Type), alpha = 0.5)+ #, color = Type)) +
  geom_point() +
  #ylim(c(0,7)) +
  xlab("Drainage Area (sqkm)")+
  scale_x_log10() +
  scale_colour_manual(values=cols)+
  theme_classic()


sizeRBImax <- ranks %>%
  ggplot(aes(x = DRAIN_SQKM, y = RBImax, color = Type)) +
  geom_point() +
  ylim(c(0,1.5)) +
  scale_x_log10()+
  theme_classic()



combined <- (sizeRBI + sizeRBImax) & theme(legend.position = "bottom")
combined + plot_layout(guides = "collect")

sizeRBI

```
```{r}
cstates <- states[!states$STUSPS %in% c("HI","AK","PR","VI","GU","MP","AS"),] 

ranks %>% filter(RBI < 2) %>%
  ggplot(aes(LNG_GAGE, LAT_GAGE, fill = RBIcv))+
  geom_polygon(data = cstates, aes(x = long, y = lat, group = group), colour = "black", fill = NA)+
    geom_point(colour = "black", pch = 21)+
   # scale_fill_gradient2()+
  scale_fill_viridis()+
  
  theme_classic()
```
```{r}
cstates <- states[!states$STUSPS %in% c("HI","AK","PR","VI","GU","MP","AS"),] 

ranks %>% 
  ggplot(aes(LNG_GAGE, LAT_GAGE, fill = log10(RBIcv)))+
  geom_polygon(data = cstates, aes(x = long, y = lat, group = group), colour = "black", fill = NA)+
    geom_point(colour = "black", pch = 21)+
   # scale_fill_gradient2()+
  scale_fill_viridis()+
  
  theme_classic()
```

